const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    padding: "20px",
    backgroundColor: "#121212",
    minHeight: "100vh",
    color: "#e0e0e0",
  },
  card: {
    backgroundColor: "#1e1e1e",
    borderRadius: "10px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.3)",
    padding: "30px",
    width: "100%",
    maxWidth: "900px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "25px",
    borderBottom: "1px solid #333",
    paddingBottom: "10px",
  },
  title: {
    color: "#ffffff",
    fontSize: "24px",
    marginBottom: "25px",
    borderBottom: "1px solid #333",
    paddingBottom: "10px",
  },
  logoutButton: {
    backgroundColor: "#e53e3e",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "10px 16px",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.3s",
  },
  subtitle: {
    color: "#ffffff",
    fontSize: "20px",
    margin: "30px 0 15px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  label: {
    color: "#bbbbbb",
    fontSize: "14px",
    fontWeight: "500",
  },
  input: {
    padding: "12px 15px",
    borderRadius: "6px",
    border: "1px solid #333",
    fontSize: "14px",
    transition: "all 0.3s",
    backgroundColor: "#2d2d2d",
    color: "#ffffff",
    outline: "none",
    ":focus": {
      borderColor: "#667eea",
      boxShadow: "0 0 0 3px rgba(102, 126, 234, 0.2)",
    },
  },
  buttonSubmit: {
    backgroundColor: "#48bb78",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "12px 20px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.3s",
    marginTop: "10px",
    ":hover": {
      backgroundColor: "#38a169",
    },
    ":disabled": {
      backgroundColor: "#2d3748",
      cursor: "not-allowed",
    },
  },
  buttonEdit: {
    backgroundColor: "#4299e1",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "12px 20px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.3s",
    marginTop: "10px",
    ":hover": {
      backgroundColor: "#3182ce",
    },
  },
  buttonCancel: {
    backgroundColor: "#e53e3e",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "12px 20px",
    fontSize: "16px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "background-color 0.3s",
    marginTop: "10px",
    ":hover": {
      backgroundColor: "#c53030",
    },
  },
  buttonContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  spinner: {
    border: "2px solid rgba(255, 255, 255, 0.3)",
    borderRadius: "50%",
    borderTop: "2px solid #ffffff",
    width: "16px",
    height: "16px",
    animation: "spin 1s linear infinite",
  },
  alertError: {
    backgroundColor: "#2d2222",
    color: "#ff6b6b",
    padding: "12px 15px",
    borderRadius: "6px",
    marginBottom: "20px",
    borderLeft: "4px solid #ff6b6b",
  },
  alertSuccess: {
    backgroundColor: "#222d22",
    color: "#68d391",
    padding: "12px 15px",
    borderRadius: "6px",
    marginBottom: "20px",
    borderLeft: "4px solid #68d391",
  },
  tableContainer: {
    overflowX: "auto",
    borderRadius: "8px",
    border: "1px solid #333",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  tableHeaderRow: {
    backgroundColor: "#2d2d2d",
  },
  tableHeader: {
    padding: "12px 15px",
    textAlign: "left",
    color: "#ffffff",
    fontWeight: "600",
    borderBottom: "1px solid #333",
  },
  tableRow: {
    borderBottom: "1px solid #333",
    ":hover": {
      backgroundColor: "#2d2d2d",
    },
  },
  tableCell: {
    padding: "12px 15px",
    color: "#e0e0e0",
  },
  tableCellActions: {
    padding: "12px 15px",
    display: "flex",
    gap: "8px",
  },
  buttonActionEdit: {
    backgroundColor: "#4299e1",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
    fontSize: "14px",
    cursor: "pointer",
    transition: "background-color 0.3s",
    ":hover": {
      backgroundColor: "#3182ce",
    },
  },
  buttonActionDelete: {
    backgroundColor: "#e53e3e",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
    fontSize: "14px",
    cursor: "pointer",
    transition: "background-color 0.3s",
    ":hover": {
      backgroundColor: "#c53030",
    },
  },
  loading: {
    textAlign: "center",
    padding: "20px",
    color: "#a0aec0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  emptyMessage: {
    textAlign: "center",
    padding: "20px",
    color: "#a0aec0",
    backgroundColor: "#2d2d2d",
    borderRadius: "6px",
  },
  "@keyframes spin": {
    "0%": { transform: "rotate(0deg)" },
    "100%": { transform: "rotate(360deg)" },
  },
};

export default styles;
